import { jsPDF } from 'jspdf'
import { STATUS_LABELS } from './constants'
import type { RequestAuditLog } from '@/lib/supabase/client'

export interface AuditPdfPayload {
  logs: RequestAuditLog[]
  requestId: string
  exportedAt: string
}

export async function generateAuditPdf({ logs, requestId, exportedAt }: AuditPdfPayload) {
  const autoTable = (await import('jspdf-autotable')).default
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 14

    // --- 1. LOGO & HEADER ---
    try {
      doc.addImage('/logo.png', 'PNG', margin, 10, 38, 14)
    } catch (e) {
      console.warn('Logo image file not found in public/logo.png, skipping image render.', e)
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text('Audit History Report', 65, 20)

    doc.setDrawColor(0, 171, 78)
    doc.setLineWidth(0.8)
    doc.line(margin, 28, pageWidth - margin, 28)

    // --- 2. METADATA ---
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Request ID:', margin, 36)
    doc.setFont('helvetica', 'normal')
    doc.text(requestId, margin + 26, 36)

    doc.setFont('helvetica', 'bold')
    doc.text('Exported On:', margin, 43)
    doc.setFont('helvetica', 'normal')
    const exportedDate = new Date(exportedAt).toLocaleString()
    doc.text(exportedDate, margin + 26, 43)

    doc.setFont('helvetica', 'bold')
    doc.text('Total Entries:', margin, 50)
    doc.setFont('helvetica', 'normal')
    doc.text(String(logs.length), margin + 26, 50)

    // --- 3. AUDIT TABLE ---
    const tableHeaders = [['#', 'Date & Time', 'User', 'Action', 'Status Transition', 'Comment']]

    const tableRows = logs.map((log, index) => {
      const prevLabel = log.previous_status
        ? STATUS_LABELS[log.previous_status as keyof typeof STATUS_LABELS] || log.previous_status
        : 'N/A'
      const nextLabel = log.new_status
        ? STATUS_LABELS[log.new_status as keyof typeof STATUS_LABELS] || log.new_status
        : 'N/A'
      const statusTransition = log.previous_status || log.new_status ? `${prevLabel} → ${nextLabel}` : '—'

      return [
        index + 1,
        log.timestamp ? new Date(log.timestamp).toLocaleString() : 'N/A',
        log.changed_by || 'SYSTEM',
        log.action,
        statusTransition,
        log.comment || '—',
      ]
    })

    autoTable(doc, {
      startY: 58,
      head: tableHeaders,
      body: tableRows,
      theme: 'grid',
      headStyles: {
        fillColor: [0, 171, 78],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center',
      },
      columnStyles: {
        0: { halign: 'center', cellWidth: 12 },
        1: { halign: 'left', cellWidth: 40 },
        2: { halign: 'left', cellWidth: 30 },
        3: { halign: 'center', cellWidth: 20 },
        4: { halign: 'left', cellWidth: 40 },
        5: { halign: 'left', cellWidth: 50 },
      },
      styles: {
        font: 'helvetica',
        fontSize: 9,
      },
      didDrawPage: () => {
        const footerY = doc.internal.pageSize.getHeight() - 20
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(8)
        doc.setTextColor(120, 120, 120)
        doc.text('Generated by Ethio Telecom CRMS', margin, footerY)
        doc.setTextColor(0, 0, 0)
      },
    })

    const cleanName = `audit_${requestId.replace(/[^a-z0-9]/gi, '_').toLowerCase()}`
    doc.save(`${cleanName}.pdf`)
  } catch (err) {
    console.error('Error generating audit PDF:', err)
  }
}
